package quranenc

import "data-quran-cli/internal/dl"

var downloadRequests = []dl.Request{{
	URL:      "https://quranenc.com/en/home/download/xml/english_saheeh",
	FileName: "english_saheeh.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/english_hilali_khan",
	FileName: "english_hilali_khan.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/english_rwwad",
	FileName: "english_rwwad.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/french_montada",
	FileName: "french_montada.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/french_rashid",
	FileName: "french_rashid.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/french_hameedullah",
	FileName: "french_hameedullah.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/spanish_garcia",
	FileName: "spanish_garcia.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/spanish_montada_eu",
	FileName: "spanish_montada_eu.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/spanish_montada_latin",
	FileName: "spanish_montada_latin.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/portuguese_nasr",
	FileName: "portuguese_nasr.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/german_bubenheim",
	FileName: "german_bubenheim.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/turkish_shaban",
	FileName: "turkish_shaban.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/turkish_rwwad",
	FileName: "turkish_rwwad.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/turkish_shahin",
	FileName: "turkish_shahin.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/albanian_nahi",
	FileName: "albanian_nahi.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/bosnian_mihanovich",
	FileName: "bosnian_mihanovich.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/bosnian_rwwad",
	FileName: "bosnian_rwwad.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/uzbek_mansour",
	FileName: "uzbek_mansour.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/tajik_arifi",
	FileName: "tajik_arifi.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/indonesian_sabiq",
	FileName: "indonesian_sabiq.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/indonesian_affairs",
	FileName: "indonesian_affairs.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/indonesian_complex",
	FileName: "indonesian_complex.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/tagalog_rwwad",
	FileName: "tagalog_rwwad.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/chinese_makin",
	FileName: "chinese_makin.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/uyghur_saleh",
	FileName: "uyghur_saleh.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/japanese_saeedsato",
	FileName: "japanese_saeedsato.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/vietnamese_rwwad",
	FileName: "vietnamese_rwwad.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/khmer_cambodia",
	FileName: "khmer_cambodia.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/persian_ih",
	FileName: "persian_ih.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/kurdish_bamoki",
	FileName: "kurdish_bamoki.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/urdu_junagarhi",
	FileName: "urdu_junagarhi.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/hindi_omari",
	FileName: "hindi_omari.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/malayalam_kunhi",
	FileName: "malayalam_kunhi.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/assamese_rafeeq",
	FileName: "assamese_rafeeq.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/tamil_omar",
	FileName: "tamil_omar.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/tamil_baqavi",
	FileName: "tamil_baqavi.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/sinhalese_mahir",
	FileName: "sinhalese_mahir.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/swahili_barawani",
	FileName: "swahili_barawani.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/amharic_sadiq",
	FileName: "amharic_sadiq.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/yoruba_mikail",
	FileName: "yoruba_mikail.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/hausa_gummi",
	FileName: "hausa_gummi.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/oromo_ababor",
	FileName: "oromo_ababor.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/afar_hamza",
	FileName: "afar_hamza.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/ankobambara_dayyan",
	FileName: "ankobambara_dayyan.xml",
}, {
	URL:      "https://quranenc.com/en/home/download/xml/kinyarwanda_assoc",
	FileName: "kinyarwanda_assoc.xml",
}}
